name: Publish Package to npmjs

on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Step 2 - Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Step 3 - Setup .npmrc file to publish to npm
      - run: npm ci

      # Step 4 - Publish to npm
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}